
MTK_SEC_SECRO_AC_SUPPORT = yes 


TARGET_ARCH_VARIANT = armv7-a-neon


MTK_ENGINEERMODE_INTERNAL_APP = yes

MTK_FIRST_MD = 1
MTK_FOTA_ENTRY = no
MTK_FLIGHT_MODE_POWER_OFF_MD = yes

MTK_SCOMO_ENTRY = no

MTK_OGM_PLAYBACK_SUPPORT = no

MTK_MTKPS_PLAYBACK_SUPPORT = no

MTK_DP_FRAMEWORK = yes
MTK_ION_SUPPORT = yes

MTK_ENABLE_MD1 = no
MTK_ENABLE_MD2 = no

MTK_FD_SUPPORT=yes

CUSTOM_KERNEL_SSW=ssw_generic

MTK_SWIP_VORBIS=yes

MULTI_CH_PLAYBACK_SUPPORT=no


MTK_PRODUCT_INFO_SUPPORT=yes

HAVE_MTKLOUDNESS_EFFECT=yes
MTK_VSS_SUPPORT = no 


MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM=yes
MTK_PQ_SUPPORT=yes    
MTK_FM_RX_AUDIO=FM_DIGITAL_INPUT

MTK_BWC_SUPPORT = yes

MTK_FLV_PLAYBACK_SUPPORT=yes


MTK_LCEEFT_SUPPORT = yes 

MTK_WFD_SUPPORT=yes


MTK_KERNEL_POWER_OFF_CHARGING = yes



MTK_BAIDU_MAP_SUPPORT = no


# Specify HDMI external IC type.
CUSTOM_KERNEL_HDMI=

# To control whether enable or disable HDMI feature. If choose yes,  phone's screen can be demonstrated on TV via HDMI cable.
MTK_HDMI_SUPPORT=no

MTK_SPM_MCDI_ENABLE = yes


MTK_VIDEO_THUMBNAIL_PLAY_SUPPORT = yes 


MTK_FENCE_SUPPORT = yes 


MTK_MD_SHUT_DOWN_NT = yes 


MTK_WAKE_LOCK_ERROR_HANDLING = yes


MTK_TENCENT_MOBILE_MANAGER_NORMAL_SUPPORT = no 


MTK_QQBROWSER_SUPPORT = no 

MTK_BATTERY_NO_HAL=yes

MTK_DISP_COMMON_PLATFORM=yes

LINUX_KERNEL_VERSION = kernel-3.4
LEGACY_DFO_GEN=yes
MTK_MD1_SUPPORT = 2
MTK_MD2_SUPPORT = 2
ALWAYSON_DFOSET = no
MTK_HWC_SUPPORT=yes
MTK_VOICE_UI_SUPPORT = yes

MTK_MERGE_INTERFACE_SUPPORT = yes

MTK_PERMISSION_CONTROL = yes
MTK_MOBILE_MANAGEMENT = yes
MTK_CAM_FACEBEAUTY_SUPPORT=yes
MTK_TRIPLE_FRAMEBUFFER_SUPPORT=yes
MTK_ENABLE_DIVX_DECODER=yes
MTK_PASSPOINT_R1_SUPPORT=no